### ISSUE TITLE
Stop publishing Marp app

### ISSUE THREAD

**Issue by yhatt** [yhatt/marp#277]
The time to stop publishing the old app has come, to save users from malicious.

#276 shows that malicious still can execute any code through remote. *We don't have motivation to apply security patch for Marp app that past 2 years since announced stopping maintainance.*

Today [Marp for VS Code](https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode) can use as an alternative of Marp app: Real-time preview, PDF export and more. VS Code has well-considered security protection.

### ToDo

- [x] Create single HTML page to announce migration to Marp Next
  - [x] Explain about secuiry risk for Marp app: #276
  - [x] Recommend to use [Marp for VS Code](https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode)
  - [x] Link to Marp Next: https://marp.app/
- [x] Erase codes from `master` branch
  - [x] ~~Store the latest codes in another branch~~ It can see in git history
- [x] Remove released archives from GitHub release
- [x] Update README.md
- [x] Close all issues and PRs
- [x] Archive repository
